name: Release

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:

    - name: Download Build Artifacts
      uses: actions/download-artifact@v2.1.0
      with:
        name: packages
        path: ./packages
    - name: Create GitHub release
      uses: marvinpinto/action-automatic-releases@v1.1.1
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: ${{ needs.build.outputs.preRelease == 'true' }}
        title: Release ${{ needs.build.outputs.version }}
        automatic_release_tag: ${{ needs.build.outputs.version }}
        files: |
          ./artifacts/*
    - name: Push to Nuget.org
      run: dotnet nuget push ${{ format('./out/DevHawk.DumpNef.{0}.nupkg', needs.build.outputs.version) }} --api-key ${{ secrets.NUGET_ORG_TOKEN }} --source https://api.nuget.org/v3/index.json
